### ISSUE TITLE
github url on hex.pm goes to 404

### ISSUE THREAD

**Issue by lowks** [fteem/excountries#1]
The `hex.pm` page for this package: https://hex.pm/packages/excountries, has an error for the url of github. It points to: https://github.com/fteem/excuntries instead of https://github.com/fteem/excountries

**Comment by fteem** [comment]
Hi @lowks,
I am aware of this, and I already [fixed](https://github.com/fteem/excountries/blob/master/mix.exs#L49) the typo and republished the package, but Hex.pm hasn't still updated the link on their site. I reached out to the team behind Hex and I am waiting on a reply.

**Comment by fteem** [comment]
Fixed.
